# Generated by Django 5.1.5 on 2025-02-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedialink',
            old_name='facebook_image',
            new_name='icon_image',
        ),
        migrations.RenameField(
            model_name='socialmedialink',
            old_name='facebook_link',
            new_name='link',
        ),
    ]
