# Generated by Django 5.1.5 on 2025-02-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_facebook_image_socialmedialink_icon_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='price_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='price_offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='prise_s1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='prise_s2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='prise_s3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='size1',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='size2',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='size3',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
