# Generated by Django 5.1.5 on 2025-02-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_subcategory_price_alter_subcategory_prise_s1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(default=1, upload_to='logos/'),
            preserve_default=False,
        ),
    ]
