# Generated by Django 5.1.5 on 2025-02-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_sitesettings_desc_alter_sitesettings_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedialink',
            old_name='icon_image',
            new_name='icon_face',
        ),
        migrations.RenameField(
            model_name='socialmedialink',
            old_name='link',
            new_name='link_face',
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='icon_insta',
            field=models.ImageField(blank=True, null=True, upload_to='social_media_images/'),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='icon_number',
            field=models.ImageField(blank=True, null=True, upload_to='social_media_images/'),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='icon_whatsapp',
            field=models.ImageField(blank=True, null=True, upload_to='social_media_images/'),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='link_insta',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='link_whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
