# Generated by Django 5.1.5 on 2025-02-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_rename_icon_image_socialmedialink_icon_face_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMediaLink',
        ),
    ]
