# Generated by Django 5.1.5 on 2025-02-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_delete_socialmedialink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='day',
            field=models.CharField(choices=[('Sun', 'الاحد'), ('Mon', 'الاثنين'), ('Tue', 'الثلاثاء'), ('Wed', 'الاربعاء'), ('Thu', 'الخميس'), ('Fri', 'الجمعه'), ('Sat', 'السبت')], max_length=3),
        ),
    ]
