# Generated by Django 5.1.5 on 2025-02-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_workinghours_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='close_period',
            field=models.CharField(choices=[('AM', 'ص'), ('PM', 'م')], default='PM', max_length=2),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='open_period',
            field=models.CharField(choices=[('AM', 'ص'), ('PM', 'م')], default='AM', max_length=2),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
