# Generated by Django 5.1.5 on 2025-02-17 20:09

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_subcategory_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('text_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
            ],
        ),
    ]
