# Generated by Django 5.1.5 on 2025-02-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_menu_delete_colors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Color',
        ),
    ]
