# Generated by Django 5.1.5 on 2025-02-18 11:07

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_rename_menu_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='name',
        ),
        migrations.AddField(
            model_name='color',
            name='color_name',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='color',
            name='color_price',
            field=colorfield.fields.ColorField(default='#FF5733', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='color',
            name='color_text',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='color',
            name='site_settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='menu.sitesettings'),
            preserve_default=False,
        ),
    ]
