# Generated by Django 5.1.5 on 2025-02-18 11:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_remove_color_name_color_color_name_color_color_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='site_settings',
        ),
        migrations.AlterField(
            model_name='color',
            name='color_price',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_text',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
