# Generated by Django 5.1.5 on 2025-02-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_sitesettings_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='extras_images/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subcategory',
            name='extras',
            field=models.ManyToManyField(blank=True, help_text='إضافات متعددة لهذا الصنف.', related_name='subcategories', to='menu.extra'),
        ),
    ]
