# Generated by Django 5.1.5 on 2025-02-24 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_extra_subcategory_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='color_scheme',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.color'),
        ),
    ]
