# Generated by Django 5.1.5 on 2025-02-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_color_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='name_en',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maincategory',
            name='name_en',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
