# Generated by Django 5.1.5 on 2025-02-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_extra_name_en_maincategory_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='site_settings',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='color_scheme',
        ),
    ]
