# Generated by Django 5.1.5 on 2025-02-24 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_remove_color_site_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='site_settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Color', to='menu.sitesettings'),
            preserve_default=False,
        ),
    ]
