# Generated by Django 5.1.5 on 2025-02-24 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_color_site_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='site_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='menu.sitesettings'),
        ),
    ]
