# Generated by Django 5.1.5 on 2025-02-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_alter_color_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='not_dound',
            field=models.BooleanField(default=False),
        ),
    ]
