# Generated by Django 5.1.5 on 2025-02-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0027_remove_subcategory_price_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='caloreis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
