# Generated by Django 5.1.5 on 2025-02-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0028_subcategory_caloreis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(max_length=50),
        ),
    ]
