# Generated by Django 5.1.5 on 2025-02-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0029_alter_subcategory_name_alter_subcategory_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_cart',
            field=models.CharField(default='#FF5733', max_length=7),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_name',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_price',
            field=models.CharField(default='#FF5733', max_length=7),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_text',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='currencies',
            field=models.CharField(choices=[('$', 'USD-الدولار الأمريكي'), ('€', 'EUR-اليورو'), ('£', 'GBP-الجنيه الإسترليني'), ('¥', 'JPY-الين الياباني'), ('CHF', 'CHF-الفرنك السويسري'), ('$', 'CAD-الدولار الكندي'), ('$', 'AUD-الدولار الأسترالي'), ('¥', 'CNY-اليوان الصيني'), ('₽', 'RUB-الروبيل الروسي'), ('SAR', 'SAR-الريال السعودي'), ('AED', 'AED-الدرهم الإماراتي'), ('QAR', 'QAR-الريال القطري'), ('EGP', 'EGP-الجنيه المصري'), ('OMR', 'OMR-الريال العماني'), ('₹', 'INR-الروبية الهندية'), ('₨', 'PKR-الروبية الباكستانية'), ('$', 'MXN-البيزو المكسيكي'), ('$', 'NZD-الدولار النيوزيلندي'), ('kr', 'SEK-الكرونة السويدية'), ('kr', 'DKK-الكرونة الدنماركية'), ('RM', 'MYR-الرينغيت الماليزي'), ('R$', 'BRL-الريال البرازيلي'), ('$', 'ARS-البيزو الأرجنتيني'), ('₪', 'ILS-الشيكل الإسرائيلي'), ('KWD', 'KWD-الدينار الكويتي'), ('BHD', 'BHD-الدينار البحريني'), ('Rp', 'IDR-الروبية الإندونيسية'), ('JOD', 'JOD-الدينار الأردني'), ('₺', 'TRY-الليرة التركية'), ('$', 'SGD-الدولار السنغافوري')], max_length=20),
        ),
    ]
