# Generated by Django 5.1.5 on 2025-03-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0030_alter_color_color_alter_color_color_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='caloreis',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
