# Generated by Django 5.1.5 on 2025-03-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0031_extra_caloreis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='caloreis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
