# Generated by Django 5.1.5 on 2025-03-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0033_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.URLField(blank=True, null=True),
        ),
    ]
