# Generated by Django 5.1.5 on 2025-03-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0034_branch_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='url',
            new_name='url_branch',
        ),
    ]
