# Generated by Django 5.1.5 on 2025-03-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0036_alter_subcategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='advanced_options',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='dynamic_pricing',
            field=models.BooleanField(default=False, help_text='هل ترغب في تفعيل التسعير الديناميكي؟'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='enable_discount',
            field=models.BooleanField(default=False, help_text='هل ترغب في تفعيل الخصم لهذه الفئة الفرعية؟'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='pricing_tiers',
            field=models.JSONField(blank=True, default=list, help_text="حدد مستويات التسعير (مثال: ['tier1': price1, 'tier2': price2])", null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='special_category',
            field=models.BooleanField(default=False, help_text='هل هذه الفئة الفرعية فئة مميزة؟'),
        ),
    ]
