# Generated by Django 5.1.5 on 2025-03-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0037_subcategory_advanced_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='advanced_options',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='dynamic_pricing',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='enable_discount',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='pricing_tiers',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='special_category',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(help_text='صورة الفئة الفرعية', max_length=50),
        ),
    ]
