# Generated by Django 5.1.5 on 2025-03-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0038_remove_subcategory_advanced_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(help_text='اسم الصنف', max_length=50),
        ),
    ]
