# Generated by Django 5.1.5 on 2025-03-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0039_alter_subcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=30, verbose_name='product name-(عربي)إسم الصنف'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='uploudImg_SubCategory',
            field=models.ImageField(blank=True, null=True, upload_to='scategory_images/', verbose_name='product image-صوره الصنف'),
        ),
    ]
