# Generated by Django 5.1.5 on 2025-03-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0040_alter_subcategory_name_alter_subcategory_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name_plural': 'Catories'},
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(max_length=30, verbose_name='product name-(انجليزي)إسم الصنف'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price - السعر'),
        ),
    ]
