# Generated by Django 5.1.5 on 2025-03-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0041_alter_maincategory_options_alter_subcategory_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'ساب'},
        ),
    ]
