# Generated by Django 5.1.5 on 2025-03-08 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0042_alter_subcategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='description',
        ),
    ]
