# Generated by Django 5.1.5 on 2025-03-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0045_alter_subcategory_caloreis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='day',
            field=models.CharField(choices=[('Sun', 'الاحد-Sun'), ('Mon', 'الاثنين'), ('Tue', 'الثلاثاء'), ('Wed', 'الاربعاء'), ('Thu', 'الخميس'), ('Fri', 'الجمعه'), ('Sat', 'السبت')], max_length=3),
        ),
    ]
