# Generated by Django 5.1.5 on 2025-03-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0046_alter_workinghours_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='is_open_24h',
            field=models.BooleanField(default=False, verbose_name='٢٤ ساعة'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='close_period',
            field=models.CharField(choices=[('AM', 'AM-      صباحا'), ('PM', 'PM-مساءا')], default='PM', max_length=2),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='day',
            field=models.CharField(choices=[('Sat', 'Sat-السبت'), ('Sun', 'Sun-الاحد'), ('Mon', 'Mon-الاثنين'), ('Tue', 'Tue-الثلاثاء'), ('Wed', 'Wed-الاربعاء'), ('Thu', 'Thu-الخميس'), ('Fri', 'Fri-الجمعه')], max_length=3),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='open_period',
            field=models.CharField(choices=[('AM', 'AM-      صباحا'), ('PM', 'PM-مساءا')], default='AM', max_length=2),
        ),
    ]
