# Generated by Django 5.1.5 on 2025-03-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0047_workinghours_is_open_24h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='day',
            field=models.CharField(choices=[('all', 'All days-كل الايام'), ('Sat', 'Sat-السبت'), ('Sun', 'Sun-الاحد'), ('Mon', 'Mon-الاثنين'), ('Tue', 'Tue-الثلاثاء'), ('Wed', 'Wed-الاربعاء'), ('Thu', 'Thu-الخميس'), ('Fri', 'Fri-الجمعه')], max_length=3),
        ),
    ]
