# Generated by Django 5.1.5 on 2025-03-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0048_alter_workinghours_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='days',
            field=models.CharField(blank=True, choices=[('all', 'All days-كل الايام'), ('Sat', 'Sat-السبت'), ('Sun', 'Sun-الاحد'), ('Mon', 'Mon-الاثنين'), ('Tue', 'Tue-الثلاثاء'), ('Wed', 'Wed-الاربعاء'), ('Thu', 'Thu-الخميس'), ('Fri', 'Fri-الجمعه')], help_text='اختر الأيام في نفس الحقل (مثال: Sat,Sun)', max_length=255, null=True),
        ),
    ]
