# Generated by Django 5.1.5 on 2025-03-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0049_workinghours_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinghours',
            name='days',
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='close_period',
            field=models.CharField(choices=[('AM', 'AM-صباحا'), ('PM', 'PM-مساءا')], default='PM', max_length=2),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='open_period',
            field=models.CharField(choices=[('AM', 'AM-صباحا'), ('PM', 'PM-مساءا')], default='AM', max_length=2),
        ),
    ]
