# Generated by Django 5.1.7 on 2025-03-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0050_remove_workinghours_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinghours',
            name='day',
        ),
        migrations.AddField(
            model_name='workinghours',
            name='days',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
