# Generated by Django 5.1.7 on 2025-03-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0052_alter_workinghours_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name_plural': 'info'},
        ),
        migrations.AddField(
            model_name='color',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
