# Generated by Django 5.1.7 on 2025-03-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0053_alter_sitesettings_options_color_is_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_color'),
        ),
    ]
