# Generated by Django 5.1.7 on 2025-03-16 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0054_color_unique_active_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_face', models.URLField(blank=True, null=True)),
                ('url_insta', models.URLField(blank=True, null=True)),
                ('url_whats', models.URLField(blank=True, null=True)),
                ('url_tiktok', models.URLField(blank=True, null=True)),
                ('location', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='color',
            name='unique_active_color',
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='يجب اختيار لون واحد فقط'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='site_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialmedia', to='menu.sitesettings'),
        ),
    ]
