# Generated by Django 5.1.7 on 2025-03-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0055_socialmedia_remove_color_unique_active_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name_plural': 'add Category -  اضافه صنف رئيسي '},
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='(AR)اسم الصنف الرئيسي / Main Category Name'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='(EN)اسم الصنف الرئيسي / Main Category Name'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
