# Generated by Django 5.1.7 on 2025-03-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0056_alter_maincategory_options_alter_maincategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=100),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_cart',
            field=models.CharField(default='#FF5733', max_length=100),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_name',
            field=models.CharField(default='#FFFFFF', max_length=100),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_price',
            field=models.CharField(default='#FF5733', max_length=100),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_text',
            field=models.CharField(default='#000000', max_length=100),
        ),
    ]
