# Generated by Django 5.1.7 on 2025-03-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0058_alter_maincategory_name_alter_maincategory_name_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': ' Branches  🔀 '},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': ' Color 🎨  '},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name_plural': 'info '},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '  Slider  🔁  '},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name_plural': ' Social 💬 '},
        ),
        migrations.AlterModelOptions(
            name='workinghours',
            options={'verbose_name_plural': ' hour 🕓  '},
        ),
        migrations.RemoveField(
            model_name='extra',
            name='image',
        ),
        migrations.AlterField(
            model_name='extra',
            name='caloreis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='عدد السعرات', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='extra',
            name='name',
            field=models.CharField(help_text='اسم الاضافه (عربي)', max_length=100, verbose_name='Extra (AR)'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='name_en',
            field=models.CharField(help_text='اسم الاضافه (انجليزي)', max_length=100, verbose_name='Extra (EN)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='currencies',
            field=models.CharField(choices=[('$', 'USD-الدولار الأمريكي'), ('€', 'EUR-اليورو'), ('£', 'GBP-الجنيه الإسترليني'), ('¥', 'JPY-الين الياباني'), ('CHF', 'CHF-الفرنك السويسري'), ('$', 'CAD-الدولار الكندي'), ('$', 'AUD-الدولار الأسترالي'), ('¥', 'CNY-اليوان الصيني'), ('₽', 'RUB-الروبيل الروسي'), ('SAR', 'SAR-الريال السعودي'), ('AED', 'AED-الدرهم الإماراتي'), ('QAR', 'QAR-الريال القطري'), ('EGP', 'EGP-الجنيه المصري'), ('OMR', 'OMR-الريال العماني'), ('₹', 'INR-الروبية الهندية'), ('₨', 'PKR-الروبية الباكستانية'), ('$', 'MXN-البيزو المكسيكي'), ('$', 'NZD-الدولار النيوزيلندي'), ('kr', 'SEK-الكرونة السويدية'), ('kr', 'DKK-الكرونة الدنماركية'), ('RM', 'MYR-الرينغيت الماليزي'), ('R$', 'BRL-الريال البرازيلي'), ('$', 'ARS-البيزو الأرجنتيني'), ('₪', 'ILS-الشيكل الإسرائيلي'), ('KWD', 'KWD-الدينار الكويتي'), ('BHD', 'BHD-الدينار البحريني'), ('Rp', 'IDR-الروبية الإندونيسية'), ('JOD', 'JOD-الدينار الأردني'), ('₺', 'TRY-الليرة التركية'), ('$', 'SGD-الدولار السنغافوري')], help_text='العمله', max_length=20, verbose_name='currencies'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='desc',
            field=models.CharField(blank=True, help_text='وصف ', max_length=100, null=True, verbose_name='brand description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='name',
            field=models.CharField(help_text='اسم المطعم', max_length=100, verbose_name='brand name'),
        ),
    ]
