# Generated by Django 5.1.7 on 2025-04-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0060_alter_extra_options_alter_maincategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='url_whats',
            field=models.CharField(blank=True, help_text='رقم الواتساب', max_length=200, null=True, verbose_name='whatsapp 💬'),
        ),
    ]
