# Generated by Django 5.1.7 on 2025-04-02 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0061_alter_socialmedia_url_whats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='phone_number',
            field=models.CharField(help_text='رقم التليفون بصيغة صحيحة (بدون رموز أو مسافات)', max_length=15, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يحتوي فقط على أرقام بدون رموز أو مسافات.', regex='^\\d{10,15}$')], verbose_name='phone number 📞'),
        ),
    ]
