# Generated by Django 5.1.7 on 2025-04-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0062_alter_socialmedia_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='product name(AR) '),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='product name(EN) '),
        ),
    ]
